version: '3.2'

services:
  python:
    image: 'qopbot/gaiabot:1.1'
    environment:
      TELEGRAM_BOT_TOKEN: ToKen
      SPARKS_CLIENT: client
      SPARKS_SECRET: secret
      SPARKS_USERNAME: username
      SPARKS_PASSWORD: password
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - BOT_REDIS_VOLUME:/bitnami/redis/data
volumes:
  BOT_REDIS_VOLUME:
    external: true
